/*
 * Generated by WEB converter:Mon Dec 14 10:35:10 CST 2015
 * Do not edit
 */
#include "web_proc.h"
#include "webpage.h"
#include "web_config.h"
#include "webdata_bin.h"

time_t time_pages_created =(1450060510+28800);
char *zweb_location = (char *)(&webdata_bin[0]);

webpage_entry webpage_table[]= {
{ "/AP.html", web__AP_html, 1391, WEBP_NORMAL, (void *)0, NULL, 0 },
{ "/index.html", web__index_html, 1580, WEBP_NORMAL, (void *)0, NULL, 0 },
{ "/Test1.html", web__Test1_html, 173, WEBP_NORMAL, (void *)0, NULL, 0 },
{ "/Test.html", web__Test_html, 328, WEBP_NORMAL, (void *)0, NULL, 0 },
{0 , NULL, 0, 0, 0, NULL, 0},
};
