/*
 * Generated by MTK Easy PinMux Tool Version 1.0.3 for 2523. Copyright MediaTek Inc. (C) 2015.
 * Thu Apr 14 09:09:10 2016
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*
* Author:
* -------
*
*============================================================================
****************************************************************************/


const unsigned char HAL_MSDC_EINT = 7;
const unsigned char HAL_ACCDET_EINT = 8;
const unsigned char BSP_GNSS_EINT = 10;
const unsigned char BSP_CTP_EINT = 13;




