/*
 * Generated by MTK Easy PinMux Tool Version 1.0.0 for 2523. Copyright MediaTek Inc. (C) 2015.
 * Tue Feb 23 19:08:50 2016
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*
* Author:
* -------
*
*============================================================================
****************************************************************************/


const char BSP_GNSS_POWER_PIN = 10;


const char BSP_CTP_EINT_PIN = 15;


const char HAL_KEYPAD_COL2_PIN = 18;


const char HAL_KEYPAD_COL0_PIN = 20;


const char HAL_KEYPAD_ROW1_PIN = 22;


const char BSP_CTP_SCL_PIN = 36;


const char BSP_CTP_SDA_PIN = 37;


const char BSP_SPEAKER_EBABLE_PIN = 45;


const char BSP_CTP_RST_PIN = 47;



/*Output for default variable names*/
/*@XXX_XX_PIN in gpio.cmp          */

const char HAL_KEYPAD_COL1_PIN = 0xff;
const char HAL_KEYPAD_ROW2_PIN = 0xff;
const char HAL_KEYPAD_ROW0_PIN = 0xff;
const char BSP_AUXADC_ENABLE_PIN = 0xff;
const char gpio_20_strapping_pin = 0xff;
const char gpio_40_strapping_pin = 0xff;
const char gpio_44_strapping_pin = 0xff;
const char gpio_46_strapping_pin = 0xff;
const char gpio_47_strapping_pin = 0xff;
const char gpio_48_strapping_pin = 0xff;




