/*
 * Generated by MTK Easy PinMux Tool Version 1.0.0 for 2523. Copyright MediaTek Inc. (C) 2015.
 * Tue Feb 23 19:08:50 2016
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*
* Author:
* -------
*
*============================================================================
****************************************************************************/


const unsigned char BSP_GNSS_EINT = 10;
const unsigned char HAL_ACCDET_EINT = 12;
const unsigned char BSP_CTP_EINT = 13;
const unsigned char HAL_MSDC_EINT = 19;




