/*
 * Generated by MTK Easy PinMux Tool Version 1.0.3 for 7687. Copyright MediaTek Inc. (C) 2015.
 * Thu Mar 31 10:40:23 2016
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*
* Author:
* -------
*
*============================================================================
****************************************************************************/


const unsigned char BSP_CTP_EINT = 0xff;
const unsigned char HAL_ACCDET_EINT = 0xff;
const unsigned char HAL_MSDC_EINT = 0xff;
const unsigned char BSP_GNSS_EINT = 0xff;




