/*
 * Generated by MTK Easy PinMux Tool Version 1.0.3 for 7687. Copyright MediaTek Inc. (C) 2015.
 * Thu Mar 31 10:40:23 2016
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*
* Author:
* -------
*
*============================================================================
****************************************************************************/



/*Output for default variable names*/
/*@XXX_XX_PIN in gpio.cmp          */

const char HAL_KEYPAD_COL2_PIN = 0xff;
const char HAL_KEYPAD_COL1_PIN = 0xff;
const char HAL_KEYPAD_COL0_PIN = 0xff;
const char HAL_KEYPAD_ROW2_PIN = 0xff;
const char HAL_KEYPAD_ROW1_PIN = 0xff;
const char HAL_KEYPAD_ROW0_PIN = 0xff;
const char BSP_CTP_SCL_PIN = 0xff;
const char BSP_CTP_SDA_PIN = 0xff;
const char BSP_CTP_RST_PIN = 0xff;
const char BSP_CTP_EINT_PIN = 0xff;
const char BSP_SPEAKER_EBABLE_PIN = 0xff;
const char BSP_AUXADC_ENABLE_PIN = 0xff;
const char BSP_GNSS_POWER_PIN = 0xff;




