/*
 * Generated by MTK Easy PinMux Tool Version 1.0.0 for 2523. Copyright MediaTek Inc. (C) 2015.
 * Tue Feb 23 19:08:50 2016
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*
* Author:
* -------
*
*============================================================================
****************************************************************************/
#ifndef  _EINT_DRV_H
#define  _EINT_DRV_H


#endif /* _EINT_DRV_H */


