/*
 * Generated by MTK Easy PinMux Tool Version 1.0.3 for 2523. Copyright MediaTek Inc. (C) 2015.
 * Thu Apr 14 09:09:10 2016
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*
* Author:
* -------
*
*============================================================================
****************************************************************************/
#ifndef  _EPT_EINT_DRV_H
#define  _EPT_EINT_DRV_H


#endif /* _EPT_EINT_DRV_H */


