/*
 * Generated by MTK Easy PinMux Tool Version 1.0.0 for 2523. Copyright MediaTek Inc. (C) 2015.
 * Wed Dec 02 14:59:15 2015
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*
* Author:
* -------
*
*============================================================================
****************************************************************************/
#ifndef  _KEYPAD_DRV_H
#define  _KEYPAD_DRV_H


#define  __DOUBLE_KEYPAD__

#if defined(__SINGLE_KEYPAD__)
#define KEYPAD_MAPPING \
DEVICE_KEY_0,\
DEVICE_KEY_1,\
DEVICE_KEY_2,\
DEVICE_KEY_3,\
DEVICE_KEY_4,\
DEVICE_KEY_5,\
DEVICE_KEY_6,\
DEVICE_KEY_7,\
DEVICE_KEY_8,\
DEVICE_KEY_9,\
DEVICE_KEY_STAR,\
DEVICE_KEY_HASH,\
DEVICE_KEY_VOL_UP,\
DEVICE_KEY_VOL_DOWN,\
DEVICE_KEY_UP,\
DEVICE_KEY_DOWN,\
DEVICE_KEY_LEFT,\
DEVICE_KEY_RIGHT,\
DEVICE_KEY_MENU,\
DEVICE_KEY_FUNCTION,\
DEVICE_KEY_SK_LEFT,\
DEVICE_KEY_SK_RIGHT,\
DEVICE_KEY_SEND,\
DEVICE_KEY_END,\
DEVICE_KEY_POWER,\
DEVICE_KEY_CLEAR,\
DEVICE_KEY_EXT_FUNC1,\
DEVICE_KEY_EXT_FUNC2,\
DEVICE_KEY_MP3_PLAY_STOP,\
DEVICE_KEY_MP3_FWD,\
DEVICE_KEY_MP3_BACK,\
DEVICE_KEY_EXT_A
#elif defined(__DOUBLE_KEYPAD__)
#define KEYPAD_MAPPING \
DEVICE_KEY_A, \
DEVICE_KEY_B, \
DEVICE_KEY_C, \
DEVICE_KEY_D, \
DEVICE_KEY_E, \
DEVICE_KEY_E, \
DEVICE_KEY_F, \
DEVICE_KEY_G, \
DEVICE_KEY_H, \
DEVICE_KEY_I, \
DEVICE_KEY_J, \
DEVICE_KEY_K, \
DEVICE_KEY_L, \
DEVICE_KEY_M, \
DEVICE_KEY_N, \
DEVICE_KEY_O, \
DEVICE_KEY_P, \
DEVICE_KEY_Q, \
DEVICE_KEY_R, \
DEVICE_KEY_S, \
DEVICE_KEY_T, \
DEVICE_KEY_U, \
DEVICE_KEY_V, \
DEVICE_KEY_W, \
DEVICE_KEY_X, \
DEVICE_KEY_Y, \
DEVICE_KEY_Z, \
DEVICE_KEY_0, \
DEVICE_KEY_ENTER, \
DEVICE_KEY_SPACE, \
DEVICE_KEY_TAB, \
DEVICE_KEY_DEL 
#endif

#define POWERKEY_POSITION DEVICE_KEY_POWER

#define DRV_KBD_COL_ROW_SEL 0x1c7

#endif /* _KEYPAD_DRV_H */


