#define WEBDATA_SZ 3472
/*
 * Generated by WEB converter:Mon Dec 14 10:35:11 CST 2015
 * Do not edit
 */
extern time_t time_pages_created;
extern webpage_entry webpage_table[];
extern const unsigned char webdata_bin[];
extern char *zweb_location;
extern int web__AP_html(struct connstruct *req, char *datap);
extern int web__index_html(struct connstruct *req, char *datap);
extern int web__Test1_html(struct connstruct *req, char *datap);
extern int web__Test_html(struct connstruct *req, char *datap);
